### ISSUE TITLE
Unfriendly error when trying to use cli flags

### ISSUE THREAD

**Issue by pdehaan** [jonschlinkert/markdown-toc#14]
I was trying to see if there were any command line options, but it seems like it assumes everything is a file/input:

```sh
$ toc
fs.js:443
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/peterdehaan/dev/github/README.md'
    at Error (native)
    at Object.fs.openSync (fs.js:443:18)
    at Object.fs.readFileSync (fs.js:309:15)
    at Object.file.readFileSync (/Users/peterdehaan/npm/lib/node_modules/marked-toc/node_modules/fs-utils/index.js:154:19)
    at Function.toc.add (/Users/peterdehaan/npm/lib/node_modules/marked-toc/index.js:130:22)
    at Object.<anonymous> (/Users/peterdehaan/npm/lib/node_modules/marked-toc/bin/toc:9:5)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)

$ toc --help
fs.js:443
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/peterdehaan/dev/github/--help'
    at Error (native)
    at Object.fs.openSync (fs.js:443:18)
    at Object.fs.readFileSync (fs.js:309:15)
    at Object.file.readFileSync (/Users/peterdehaan/npm/lib/node_modules/marked-toc/node_modules/fs-utils/index.js:154:19)
    at Function.toc.add (/Users/peterdehaan/npm/lib/node_modules/marked-toc/index.js:130:22)
    at Object.<anonymous> (/Users/peterdehaan/npm/lib/node_modules/marked-toc/bin/toc:9:5)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
```

Not sure if you want to throw a `fs.exists()` or `fs.existsSync()` into the mix to ensure that said file/path exists before trying to use it.

**Comment by jonschlinkert** [comment]
project was refactored
