### ISSUE TITLE
Error in slugify() method with version 0.12.9

### ISSUE THREAD

**Issue by rogierschouten** [jonschlinkert/markdown-toc#56]
```
$ node
> var toc = require("markdown-toc")
undefined
> toc.slugify("Administrator's Guide")
TypeError: Cannot read property 'seen' of undefined
    at Function.slugify (C:\Source\eXLent_master\exlent\node_modules\markdown-toc\index.js:202:12)
    at repl:1:5
    at REPLServer.defaultEval (repl.js:260:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:429:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
```

**Comment by rogierschouten** [comment]
The code at index.js:202 doesn't seem to account for the case where the third argument is not supplied.  My current workaround:

```
toc.slugify("Administrator's Guide", undefined, {})
```

**Comment by jonschlinkert** [comment]
Thanks for reporting, this is a regression introduced in https://github.com/jonschlinkert/markdown-toc/commit/e2e2f329eb064a3502fb02dc264510c7ffc948cc

**Comment by jonschlinkert** [comment]
@rogierschouten want to do a pr? If not I can fix as soon as I get a chance
