### ISSUE TITLE
`linkify()` should escape the `tok.content`

### ISSUE THREAD

**Issue by twang2218** [jonschlinkert/markdown-toc#67]
The current `linkify()` code at <https://github.com/jonschlinkert/markdown-toc/blob/master/index.js#L178>

```js
/**
 * Turn headings into anchors
 */

function linkify(tok, opts) {
  if (tok && tok.content) {
    var text = titleize(tok.content, opts);
    var slug = utils.slugify(tok.content, opts);
    if (tok.seen) {
      slug += '-' + tok.seen;
    }
    if (opts && typeof opts.linkify === 'function') {
      return opts.linkify(tok, text, slug, opts);
    }
    tok.content = utils.mdlink(text, '#' + slug);
  }
  return tok;
}
```

I think that the `slug` should be `querystring.escape(slug)`, otherwise the CJK characters may not correctly escaped for the generated URL.

**Comment by jonschlinkert** [comment]
sorry for the late reply, want to do a pr?

**Comment by jonschlinkert** [comment]
related https://github.com/jonschlinkert/markdown-toc/issues/58

**Comment by twang2218** [comment]
@jonschlinkert Sure, I will do the PR.
And, regarding to the #58, I will check it as well.

**Comment by twang2218** [comment]
After applied `querystring.escape(slug)`, one of the existing test failed:

```bash
  1) toc.insert should accept options:

      AssertionError: expected '---\nname: Test\n---\n# Test\n\n> This is a test!\n\n<!-- toc -->\n\n- [Quickstart](#quickstart)\n- [Options](#options)\n- [Usage examples](#usage%20examples)\n- [Contributing](#contributing)\n- [Author](#author)\n\n<!-- tocstop -->\n\n## Quickstart\nThis is the quickstart section.\n\n## Options\nThis is the options section.\n\n## Usage examples\nThis is the usage examples section.\n\n## Contributing\nThis is the Contributing section.\n\n## Author\nThis is the Author section.' to be '---\nname: Test\n---\n# Test\n\n> This is a test!\n\n<!-- toc -->\n\n- [Quickstart](#quickstart)\n- [Options](#options)\n- [Usage examples](#usage examples)\n- [Contributing](#contributing)\n- [Author](#author)\n\n<!-- tocstop -->\n\n## Quickstart\nThis is the quickstart section.\n\n## Options\nThis is the options section.\n\n## Usage examples\nThis is the usage examples section.\n\n## Contributing\nThis is the Contributing section.\n\n## Author\nThis is the Author section.'
      + expected - actual

       <!-- toc -->

       - [Quickstart](#quickstart)
       - [Options](#options)
      -- [Usage examples](#usage%20examples)
      +- [Usage examples](#usage examples)
       - [Contributing](#contributing)
       - [Author](#author)

       <!-- tocstop -->

      at Assertion.fail (node_modules/should/lib/assertion.js:92:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:164:19)
      at Context.<anonymous> (test/test.js:377:17)
```

The test case is:

```js
  it('should accept options', function() {
    var str = read('test/fixtures/insert.md');
    strip(toc.insert(str, { slugify: function(text) {
      return text.toLowerCase();
    }})).should.equal(read('test/expected/insert-options.md'));
  });
```

It's replaced the `slugify()` with a custom function, which just convert to the lower case. And for `# Usage examples`, it will convert to `usage example`, which has a SPACE in it. 

I think it's a bug in the test case, should I fix the expected value to `usage%20example`? or add a special case in `linkify()`? Which one do you think should be the expected value?

**Comment by jonschlinkert** [comment]
> I think it's a bug in the test case

agreed

**Comment by twang2218** [comment]
#58 maybe a different problem, I will try to follow that bug.
